/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hms.view;

/**
 *
 * @Atia Azmi
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addTestMenu = new javax.swing.JMenuItem();
        sea5rchTestMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Welcome to Our Hospital Management Software: Shifa(Aroggo)!");

        jMenu1.setText("Home ");

        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Lab Test");
        jMenu2.setBorderPainted(false);

        addTestMenu.setText("Add Test");
        addTestMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addTestMenuMouseClicked(evt);
            }
        });
        addTestMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTestMenuActionPerformed(evt);
            }
        });
        jMenu2.add(addTestMenu);

        sea5rchTestMenu.setText("Search Test");
        sea5rchTestMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sea5rchTestMenuMouseClicked(evt);
            }
        });
        sea5rchTestMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sea5rchTestMenuActionPerformed(evt);
            }
        });
        jMenu2.add(sea5rchTestMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        }
        private void CancelButton2ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void addTestMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTestMenuActionPerformed
        new LabTestSetup().setVisible(true);
    }//GEN-LAST:event_addTestMenuActionPerformed

    private void sea5rchTestMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sea5rchTestMenuActionPerformed
        // TODO add your handling code here:
        new PathologicalTestSearch().setVisible(true);
    }//GEN-LAST:event_sea5rchTestMenuActionPerformed

    private void addTestMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTestMenuMouseClicked
        
        new LabTestSetup().setVisible(true);
        
    }//GEN-LAST:event_addTestMenuMouseClicked

    private void sea5rchTestMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sea5rchTestMenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sea5rchTestMenuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addTestMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem sea5rchTestMenu;
    // End of variables declaration//GEN-END:variables

    public void SetVisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
